repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args:
          - "--py39-plus"
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/python/black
    rev: 24.1.1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
          flake8-docstrings,
          flake8-builtins,
          flake8-comprehensions,
          flake8-print,
          flake8-eradicate,
          flake8-requirements,
        ]
##        args: [
###          --project-base-module=cloudshell.cp.cloudstack,
##          "--known-modules=cloudshell-cp-core:[cloudshell.cp.core],cloudshell-shell-standards:[cloudshell.shell.standards],cloudshell-shell-connectivity-flow:[cloudshell.shell.flows.connectivity],cloudshell-shell-core:[cloudshell.shell.core],cloudshell-automation-api:[cloudshell.api]]"
##        ]
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.8.0
#    hooks:
#      - id: mypy
#        additional_dependencies: [types-attrs, types-requests]
#        exclude: ^tests/
#        args:
#          - "--ignore-missing-imports"
#          - "--no-warn-no-return"
#          - "--no-warn-call-arg"
